runtime: python312  
entrypoint: gunicorn -w 4 app:app  
instance_class: F1  # Choose the instance class that best fits your budget and performance needs

automatic_scaling:
  min_idle_instances: 0  # Minimum number of idle instances
  max_idle_instances: automatic  # Maximum number of idle instances (let App Engine decide)
  min_pending_latency: automatic  # Minimum latency before scaling up
  max_pending_latency: automatic  # Maximum latency before scaling down
  max_concurrent_requests: 3  # Maximum number of concurrent requests

handlers:
- url: /.*  # All URLs are handled by the app
  script: auto
  secure: always  # Force HTTPS

env_variables:
  PORT: 8080  # Standard port for GCP App Engine
