service: danish-car-price-predictor # Name of the app
runtime: python312 
instance_class: F4

entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT 

handlers:
- url: /.*
  script: auto  # Automatically route requests to the application
  secure: always  # Force HTTPS

automatic_scaling:
  # When the app uses 85% of its allocated CPU, App Engine will start creating more instances
  target_cpu_utilization: 0.85  
  min_instances: 0
  max_instances: 1
  # No more than 5 requests at the same time
  max_concurrent_requests: 5

